name: "Static Analysis"

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '.github/**'

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.33.0
      with:
        php-version: 8.1
        tools: composer:v2
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # v3.0.0
      with:
        dependency-versions: lowest

    - name: Run PHPStan
      run: composer run-script phpstan -- --no-progress
